# development:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: ENV["username"]
#   :password: ENV["password"]
#   :enable_starttls_auto: true
# production:
#   :address: smtp.gmail.com
#   :port: 587
#   :authentication: plain
#   :user_name: ENV["username"]
#   :password: ENV["password"]
#   :enable_starttls_auto: true